server:
  host: 127.0.0.1
  port: 1234
  mode: release

swagger:
  title: Golang Web Server API
  description: This is a my backend server.
  version: v1
  basePath: v1
  schemes:
    - https
    - http

log:
  logLevel: debug
  logFilename: server.log

mysql:
  host: 192.168.1.102
  port: 3306
  user: gsh
  password: gsh123
  admin:
    database: golang_server

redis:
  host: 192.168.1.102
  port: 6379
  password: gsh123
  protocol: tcp