server:
  host: 127.0.0.1
  port: 1234
  mode: release

swagger:
  title: Golang Web Server API
  description: This is a my backend server.
  version: v1
  basePath: /v1/admin
  schemes:
    - https
    - http

log:
  logLevel: debug
  logFilename: server.log

mysql:
  host: 192.168.1.102
  port: 3306
  user: gsh
  password: gsh123
  admin:
    database: golang_server

redis:
  host: 192.168.1.102
  port: 6379
  password: gsh123
  protocol: tcp
  max_idle: 10
  max_active: 1024
  idle_timeout: 240
  timeout: 20
  #  redis 默认有 16 个数据库，从 0-15
  database: 0
  secret: abcdefg1234567

cookie:
  name: golang_server

csrf:
  csrfSecret: myCsrfSecret
  csrfSalt: myCsrfSalt
  csrfToken: myCsrfToken